import { mkdir, writeFile, stat } from 'node:fs/promises'
import { join } from 'node:path'
import type { CommandContext } from '../index.js'

const README_TEMPLATE = `# .koncept/

This folder holds the **concept graph** for this project — a curated set of
semantic anchors (behavioral invariants, architectural decisions, data flows,
ui patterns, naming conventions) that AI agents and humans can read before
making changes.

## Layout

\`\`\`
.koncept/
├── concepts/   YAML files — one concept per file
├── index.json  Generated by \`koncepto verify\`. Do not hand-edit.
└── README.md   This file.
\`\`\`

## Workflow

1. Create concepts under \`concepts/<id>.yaml\` using the schema (see docs).
2. Run \`koncepto verify\` to validate parse + cross-refs + paths.
3. Commit \`.koncept/\` so AI agents and teammates see the graph.

Concepts MUST be version-controlled. The index is regenerated, but commit it
so CI / agents have a fast lookup without re-indexing.
`

export async function runInit(ctx: CommandContext): Promise<number> {
  const root = join(ctx.rootDir, '.koncept')
  const concepts = join(root, 'concepts')
  const indexFile = join(root, 'index.json')
  const readme = join(root, 'README.md')

  await mkdir(concepts, { recursive: true })
  if (!(await fileExists(indexFile))) {
    await writeFile(indexFile, '[]\n', 'utf-8')
  }
  if (!(await fileExists(readme))) {
    await writeFile(readme, README_TEMPLATE, 'utf-8')
  }

  process.stdout.write(`koncepto: initialized ${root}\n`)
  return 0
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}
