import { mkdir, writeFile, stat } from 'node:fs/promises'
import { join } from 'node:path'
import type { CommandContext } from '../index.js'

const README_TEMPLATE = `# .koncept/

This folder holds the **concept graph** for this project — a curated set of
semantic anchors (behavioral invariants, architectural decisions, data flows,
ui patterns, naming conventions) that AI agents and humans can read before
making changes.

## Layout

\`\`\`
.koncept/
├── concepts/    YAML files — one concept per file (indexed)
├── EXAMPLE.yaml Reference concept showing every field. NOT indexed.
├── index.json   Generated by \`koncepto verify\`. Do not hand-edit.
└── README.md    This file.
\`\`\`

## Concept schema (v0.1)

Each \`concepts/<id>.yaml\` MUST validate against this shape:

| Field              | Type                            | Required | Notes                                                                     |
| ------------------ | ------------------------------- | -------- | ------------------------------------------------------------------------- |
| \`id\`               | kebab-case string               | yes      | Must match \`^[a-z][a-z0-9-]+$\` and be unique across the registry.         |
| \`name\`             | string                          | yes      | Human-readable title.                                                     |
| \`type\`             | enum                            | yes      | \`behavioral-invariant\` \\| \`architectural-decision\` \\| \`data-flow\` \\| \`ui-pattern\` \\| \`naming-convention\`. |
| \`status\`           | enum                            | no       | \`active\` (default) \\| \`deprecated\` \\| \`superseded\`.                       |
| \`description\`      | string                          | yes      | Why this concept exists; what changing it would break.                    |
| \`source_of_truth\`  | { file, symbol? }               | yes      | The single file (and optionally symbol) that defines the concept.         |
| \`participants\`     | [{ file, role, purpose }]       | no       | Files that participate. \`role\` ∈ \`writer\` \\| \`reader\` \\| \`tester\` \\| \`docs\`. |
| \`invariants\`       | [{ id, description, severity, automated_check }] | no | Properties that MUST hold. \`severity\` ∈ \`high\` \\| \`medium\` \\| \`low\`.    |
| \`risks_if_broken\`  | [string]                        | no       | What goes wrong when an invariant is violated.                            |
| \`related_concepts\` | [kebab-id]                      | no       | Cross-references to other concept ids in this registry.                   |
| \`tags\`             | [string]                        | no       | Free-form tags for search/filter.                                         |
| \`created\`          | ISO date string                 | yes      | When the concept was first authored.                                      |
| \`last_updated\`     | ISO date string                 | yes      | When it was last revised.                                                 |
| \`captured_by\`      | string                          | no       | Who/what authored it (e.g. \`@alice\`, \`koncepto-trial\`).                   |
| \`references\`       | [string]                        | no       | External links / file paths providing context.                            |

See \`EXAMPLE.yaml\` (sibling of this README) for a fully-populated reference.
Full Zod schema: \`@yourtechtribe-labs/koncept-core\` → \`ConceptSchema\`.

## Workflow

1. Copy \`EXAMPLE.yaml\` into \`concepts/<your-id>.yaml\` and edit.
2. Run \`koncepto verify\` to validate parse + cross-refs + paths.
3. Commit \`.koncept/\` so AI agents and teammates see the graph.

Concepts MUST be version-controlled. The index is regenerated, but commit it
so CI / agents have a fast lookup without re-indexing.
`

const EXAMPLE_TEMPLATE = `# Reference concept — sits OUTSIDE concepts/ so it is not indexed.
# Copy this file into concepts/<your-id>.yaml and edit.
#
# Every required field is filled in; optional fields are commented to show
# their shape. See ../README.md for field-by-field documentation.

id: example-concept
name: Example concept (rename me)
type: behavioral-invariant   # behavioral-invariant | architectural-decision | data-flow | ui-pattern | naming-convention
status: active               # active (default) | deprecated | superseded
description: >
  One paragraph explaining the concept. Why does it exist? What invariants
  does it enforce? What would break if a future change violated it?

source_of_truth:
  file: src/path/to/canonical.ts
  # symbol: someExportedFunction   # optional — narrow to a symbol within the file

participants:
  - file: src/path/to/canonical.ts
    role: writer               # writer | reader | tester | docs
    purpose: Defines the behavior protected by this concept.
  - file: tests/canonical.test.ts
    role: tester
    purpose: Locks in the invariants below.

invariants:
  - id: example-invariant
    description: A property that MUST hold across the participants above.
    severity: high             # high | medium | low
    automated_check: false     # true if a test/CI rule already enforces this

risks_if_broken:
  - What goes wrong if a future change silently violates the invariant.

related_concepts: []           # list of kebab-case ids of sibling concepts
# related_concepts:
#   - some-other-concept

tags:
  - example
  - documentation

created: '2026-01-01'
last_updated: '2026-01-01'
captured_by: koncepto-init
references:
  - https://example.com/spec
`

export async function runInit(ctx: CommandContext): Promise<number> {
  const root = join(ctx.rootDir, '.koncept')
  const concepts = join(root, 'concepts')
  const indexFile = join(root, 'index.json')
  const readme = join(root, 'README.md')
  const example = join(root, 'EXAMPLE.yaml')

  await mkdir(concepts, { recursive: true })
  if (!(await fileExists(indexFile))) {
    await writeFile(indexFile, '[]\n', 'utf-8')
  }
  if (!(await fileExists(readme))) {
    await writeFile(readme, README_TEMPLATE, 'utf-8')
  }
  if (!(await fileExists(example))) {
    await writeFile(example, EXAMPLE_TEMPLATE, 'utf-8')
  }

  process.stdout.write(`koncepto: initialized ${root}\n`)
  return 0
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}
